apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs
spec:
  replicas: 2
  selector:
    matchLabels:
       app: uber
  template:
    metadata:
      name: my-app-pod
      labels:
        app: uber
        type: front-end
    spec:
      containers:
      - name: my-container
        image: 533267026736.dkr.ecr.us-east-1.amazonaws.com/test:latest  
